# version: '3.3'

# services:
#     fastapi:
#         #platform: Linux/UNIX
#         build: fastapi/
#         command: uvicorn main:app --host 0.0.0.0 --port 8008
#         volumes:
#             - ./:/usr/src/app
#         ports: 
#             - 8008:8008 
#         networks:
#             - deploy_network
#         container_name: fastapi

#     streamlit:
#         #platform: Linux/UNIX
#         build: streamlit/
#         command: streamlit run main.py
#         volumes:
#             - ./:/usr/src/app
#         depends_on:
#             - fastapi
#         ports: 
#             - 80:8501
            
#         networks:
#             - deploy_network
#         container_name: streamlit

# networks:
#     deploy_network:
#         driver: bridge
        
        
        
version: "3.7"

services:
  fastapi:
    build: fastapi
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend
    volumes:
        - ./fastapi:/app
        - ./storage:/storage

  streamlit:
    build: streamlit
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - streamlit.docker
    volumes:
      - ./streamlit:/app
      - ./storage:/storage



networks:
  AIservice:
    external: true
